name: legi
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.3
  http: ^0.12.0+1
  splashscreen:
  carousel_pro: ^0.0.13
  flutter_html: ^0.10.1+hotfix.1
  # bmnav: ^0.3.4
  fancy_bottom_navigation: ^0.3.2
  intl: ^0.15.8
  charts_flutter: ^0.6.0
  percent_indicator: "^1.0.16"
  image_picker: "^0.4.5"
  toast: ^0.1.3
  mailer: ^2.3.0
  share: ^0.5.2
  # flutter_html_view: ^0.5.11
  progress_dialog: ^1.1.0+1
  path_provider: "^0.4.1"
  image: "^2.0.4"
  flutter_masked_text: ^0.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1
  flutter_launcher_icons: "^0.7.2"
    
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/launcher.png"
    


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.jpg
    - assets/login_logo.png
    - assets/images/ede581967c723778d5332717ac56e0c7.png
    - assets/images/DSC_0217.jpg
    - assets/images/tb_slide_1.jpg
    - assets/images/tb_slide_2.jpg
    - assets/images/a.jpeg
    - assets/images/b.jpeg
    - assets/images/c.jpeg
    - assets/images/d.jpeg
    - assets/images/letsgiving.png
    - assets/images/letgiving-square.png
    - assets/images/launcher.png
    
fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf